import type { Metadata } from "next";
import { Inter, Overpass } from "next/font/google";
import "./globals.css";

const overpass = Overpass({ subsets: ["latin"], preload: true });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={overpass.className}>{children}</body>
    </html>
  );
}
